CREATE TABLE IF NOT EXISTS product(
	id BIGINT PRIMARY KEY ,
	created_at CURRENT_TIMESTAMP NOT NULL,
	title VARCHAR(100) NOT NULL,
	description TEXT NOT NULL,
	price BIGINT NOT NULL,
	category VARCHAR(30) NOT NULL,
	image TEXT NULL NOT NULL,
	rating_rate FLOAT NOT NULL,
    rating_count BIGINT NOT NULL
);


CREATE TABLE IF NOT EXISTS users (
	id TEXT NOT NULL,
	username VARCHAR(30) NOT NULL UNIQUE,
	email TEXT NOT NULL UNIQUE,
	password TEXT NOT NULL
);

