CREATE TABLE IF NOT EXISTS product(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	created_at DATETIME NOT NULL,
	title VARCHAR(100) NOT NULL,
	description TEXT NOT NULL,
	price BIGINT NOT NULL,
	category VARCHAR(30) NOT NULL,
	image TEXT NULL NOT NULL,
	rating_rate FLOAT NOT NULL,
    rating_count BIGINT NOT NULL
);


CREATE TABLE IF NOT EXISTS users (
	id TEXT NOT NULL,
	username VARCHAR(30) NOT NULL UNIQUE,
	email TEXT NOT NULL UNIQUE,
	password TEXT NOT NULL,
	created_at DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS admins(
	id TEXT NOT NULL,
	email TEXT NOT NULL,
	password TEXT NOT NULL,
	created_at DATETIME NOT NULL
);